# What is PyTorch?

PyTorch is a scientific computing package targeted at two sets of audiences:
* A replacement for NumPy to use the power of GPUs
* A deep learning research platform that provides maxium flexibility and speed

## Geting Started

### Tensors

Tensors are similar to NumPy's ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.



In [1]:
from __future__ import print_function
import torch


### Note

An uninitialized matrix is declared, but does not contain definite known values before it is used.  When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

Construct a 5x3 matrix, uninitialized:

In [2]:
x = torch.empty(5, 3)
print(x)


tensor([[3.2483e+33, 1.9690e-19, 6.8589e+22],
        [1.3340e+31, 1.1708e-19, 7.2128e+22],
        [9.2216e+29, 7.5546e+31, 1.6932e+22],
        [3.0728e+32, 2.9514e+29, 2.8940e+12],
        [7.5338e+28, 1.8037e+28, 3.4740e-12]])


Contruct a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
print(x)


tensor([[0.3913, 0.5791, 0.9904],
        [0.8914, 0.3474, 0.6645],
        [0.5715, 0.8823, 0.6613],
        [0.2895, 0.4802, 0.6258],
        [0.1601, 0.7155, 0.6445]])


Construct a matrix filled with zeros of dtype long:

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:

In [5]:
x = torch.tensor([5.5, 3])
print(x)


tensor([5.5000, 3.0000])


Or create a tensor based on an existing tensor.  These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by the user:

In [6]:
# new_* methods take in sizes
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
print()

# Override dtype
x = torch.randn_like(x, dtype=torch.float)
print(x)
print()

print('Size of x:')
print(x.size())


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

tensor([[-1.1271, -0.4662,  0.5338],
        [-0.7125,  0.1801, -0.3349],
        [-0.6669,  0.4518, -0.7735],
        [-1.0813,  1.1374,  0.7563],
        [ 0.7499, -0.1221, -1.6144]])

Size of x:
torch.Size([5, 3])


### Operations

There are multiple syntaxes for operations.  In the following example, we will take a look at the addition operation.

In [10]:
# Addition: syntax 1
y = torch.rand(5, 3)
print(x + y)

# Addition: syntax 2
print(torch.add(x, y))

# Addition: providing an output tensor as an
# argument:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# Addition in place:
y.add_(x)
print(y)


tensor([[-0.4421, -0.1935,  1.2494],
        [-0.2603,  0.2766,  0.1147],
        [-0.6074,  0.5722, -0.0494],
        [-0.9110,  1.6666,  1.5706],
        [ 1.0986,  0.5457, -1.4470]])
tensor([[-0.4421, -0.1935,  1.2494],
        [-0.2603,  0.2766,  0.1147],
        [-0.6074,  0.5722, -0.0494],
        [-0.9110,  1.6666,  1.5706],
        [ 1.0986,  0.5457, -1.4470]])
tensor([[-0.4421, -0.1935,  1.2494],
        [-0.2603,  0.2766,  0.1147],
        [-0.6074,  0.5722, -0.0494],
        [-0.9110,  1.6666,  1.5706],
        [ 1.0986,  0.5457, -1.4470]])
tensor([[-0.4421, -0.1935,  1.2494],
        [-0.2603,  0.2766,  0.1147],
        [-0.6074,  0.5722, -0.0494],
        [-0.9110,  1.6666,  1.5706],
        [ 1.0986,  0.5457, -1.4470]])


### Note:

Any operation that mutates a tensor in-place is post-fixed with an `_`.  For example `x.copy_(y)`, `x.t_()`, will change `x`.


### Indexing

You can use standard NumPy-like indexing with all bells and whistles!


In [11]:
print(x[:, 1])

tensor([-0.4662,  0.1801,  0.4518,  1.1374, -0.1221])


### Resizing

If you want to resize or reshape the tensor you can use `torch.view`:


In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())


torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use `.item()` to get the value as a Python number:

In [14]:
x = torch.randn(1)
print(x)
print(x.item())


tensor([0.4414])
0.4414212107658386


## NumPy Bridge

Converting a Torch Tensor to a NumPy array and vice versa is easy.  The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

### Converting a Torch Tensor to a NumPy Array


In [17]:
# Create a numpy array from a torch tensor
a = torch.ones(5)
print(a)

b = a.numpy()

# Note the numpy array changed in value
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

See how changing the np array changed the Torch Tensor automatically

In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## Cuda Tensors

Tensors can be moved onto any device using the `.to` method.


In [19]:

# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU

if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))


tensor([1.4414], device='cuda:0')
tensor([1.4414], dtype=torch.float64)
